// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVb5whIZdsWNAeJtyxGJgPAwrYjcLyWNM',
    appId: '1:555308609426:web:1e25abfdf437297824db4b',
    messagingSenderId: '555308609426',
    projectId: 'meetradius-ae49c',
    authDomain: 'meetradius-ae49c.firebaseapp.com',
    storageBucket: 'meetradius-ae49c.firebasestorage.app',
    measurementId: 'G-NTXVQZFJ6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF5XHNyF9gsoe6aDoOJVgueJrN7sN33rc',
    appId: '1:555308609426:android:33880fc9797d4dc424db4b',
    messagingSenderId: '555308609426',
    projectId: 'meetradius-ae49c',
    storageBucket: 'meetradius-ae49c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjIx5YMx8OfY1wkuPdy8e-0MHITDV4KhU',
    appId: '1:555308609426:ios:e0aa054af47f1ce924db4b',
    messagingSenderId: '555308609426',
    projectId: 'meetradius-ae49c',
    storageBucket: 'meetradius-ae49c.firebasestorage.app',
    iosBundleId: 'com.example.meetRadius',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjIx5YMx8OfY1wkuPdy8e-0MHITDV4KhU',
    appId: '1:555308609426:ios:e0aa054af47f1ce924db4b',
    messagingSenderId: '555308609426',
    projectId: 'meetradius-ae49c',
    storageBucket: 'meetradius-ae49c.firebasestorage.app',
    iosBundleId: 'com.example.meetRadius',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVb5whIZdsWNAeJtyxGJgPAwrYjcLyWNM',
    appId: '1:555308609426:web:69640eec0376a8c124db4b',
    messagingSenderId: '555308609426',
    projectId: 'meetradius-ae49c',
    authDomain: 'meetradius-ae49c.firebaseapp.com',
    storageBucket: 'meetradius-ae49c.firebasestorage.app',
    measurementId: 'G-FEGMFE962G',
  );

}